# Generated by Django 3.1.5 on 2021-01-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
